import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/widgets/header';
import { Footer } from '@/widgets/footer';
import { fetchServiceMenu } from '@/features/service-menu';
import { fetchMainMenu, fetchAdditionalMenu } from '@/entities/main-menu';
import { fetchContacts } from '@/entities/contact';
import { fetchSocialNetworks } from '@/entities/social-network';
import { fetchContactPersons } from '@/widgets/contact-banner/model/api';
import { headers } from 'next/headers';
import clsx from 'clsx';
import DarkProvider from '@/shared/lib/context/providers/DarkProvider';
import { darkPages } from '@/shared/lib/constants';
import GlowBorderButton from '@/shared/ui/glowborder-button/GlowBorderButton';
import NavigationProvider from '@/shared/lib/context/providers/NavigationProvider';

const font = localFont({
  adjustFontFallback: 'Arial',
  display: 'swap',
  src: [
    {
      path: '../../public/fonts/Graphik-Black-Web.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Graphik-Bold-Web.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Graphik-Medium-Web.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Graphik-Regular-Web.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Digital-агентство Мэйк',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serviceMenu = await fetchServiceMenu();
  const mainMenu = await fetchMainMenu();
  const additionalMenu = await fetchAdditionalMenu();
  const contacts = await fetchContacts();
  const socialNetworks = await fetchSocialNetworks();
  const contactPersons = await fetchContactPersons();

  const pathname = headers().get('x-pathname') ?? '/';

  return (
    <NavigationProvider>
      <DarkProvider>
        <html lang='ru'>
          <body className={clsx(font.className, { dark: darkPages.includes(pathname) })}>
            <Header
              serviceMenu={serviceMenu}
              mainMenu={mainMenu}
              contacts={contacts}
              socialNetworks={socialNetworks}
              contactPersons={contactPersons}
              additionalMenu={additionalMenu}
            />
            {children}
            <Footer />
            <GlowBorderButton />
          </body>
        </html>
      </DarkProvider>
    </NavigationProvider>
  );
}
